import { library } from '@fortawesome/fontawesome-svg-core';

import { 
  faMagnifyingGlass,
  faUser,
  faCartShopping,
  faPhone,
  faXmark, 
  faGear,
  faShop,
  faBars,
  faLocationDot,
  faPaperPlane,
  faCheck,
  faPercent,
  faCreditCard,
  faAngleLeft,
  faAngleRight,
  faStar,
  faHeart,
  faRuble,
  faTrash, 
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faMagnifyingGlass,
  faUser,
  faCartShopping,
  faPhone,
  faXmark,
  faGear,
  faShop,
  faBars,
  faLocationDot,
  faPaperPlane,
  faCheck,
  faPercent,
  faCreditCard,
  faAngleLeft,
  faAngleRight,
  faStar,
  faHeart,
  faRuble,
  faTrash
 );