'use client';

import type { Metadata } from 'next';
import { Basis } from '@/components/';
import Providers from '@/redux/Provider';
import fav from '@/pict/all/Bike-icon_30351.ico';



export const metadata: Metadata = {
  title: 'Hello',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }:
  { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href={fav.src} type="image/x-icon" />
        <title>Катись - фейк магазин</title>
      </head>
      <body>
        <Providers>
            <Basis>
              {children}
            </Basis>
        </Providers>
      </body>
    </html>
  )
}
